apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  DB_USER: c2FoaWwxNDMx # This should be the base64 encoded value of 'sahil1431'
  DB_PASS: bXlwYXNzd29yZA== # This should be the base64 encoded value of 'mypassword'
