apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-load
  template:
    metadata:
      labels:
        app: cpu-load
    spec:
      containers:
      - name: cpu-load
        image: vish/stress
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        args:
        - -cpus
        - "4"