apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do wget -q -O- http://35.200.176.157/api/endpoint; done"]
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "500m"
